<?php
include_once(dirname(__FILE__)."/configuration.php");
include_once(dirname(__FILE__)."/user.php");
include_once(dirname(__FILE__)."/languages.php");
include_once(dirname(__FILE__)."/translations.php");
include_once(dirname(__FILE__)."/functions.php");
include_once(dirname(__FILE__)."/event.php");
include_once(dirname(__FILE__)."/template.php");
?>
